- name: Maven Cache
  # You may pin to the exact commit or the version.
  # uses: skjolber/maven-cache-github-action@9f54dbd468d53eb2ac8f46864b5880e28d9100a9
  uses: skjolber/maven-cache-github-action@v1.1
  with:
    # Build step step, i.e. restore or save
    step: Build and Test
    # Maximum git history depth to search for changes to build files. Defaults to 100 commits.
    depth: # optional
    # The chunk size used to split up large files during upload, in bytes
    upload-chunk-size: # optional
    step: Security scan
    # Maximum git history depth to search for changes to build files. Defaults to 100 commits.
    depth: # optional
    # The chunk size used to split up large files during upload, in bytes
    upload-chunk-size: # optional
